modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="ARR"
[[mods]] #mandatory
modId="smarthoppers" #mandatory
version="22w16c"
issueTrackerURL=""
displayName="Smart Hoppers" #mandatory
logoFile="icon.png"
authors="Cataclysmic_Finale(Final_Cataclysm)" #optional
credits=""
description='''Hoppers but smarter!'''
[[dependencies.smarthoppers]] #optional
# the modid of the dependency
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[37,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.smarthoppers]]
modId="minecraft"
mandatory=true
versionRange="[1.17,)"
ordering="NONE"
side="BOTH"